---

- include_tasks: change_splunk_password.yml

- include_tasks: phantom_server_configure.yml
  when: phantom_server == "1" and not cloud_provider == "local"

- include_tasks: phantom_server_configure_local.yml
  when: phantom_server == "1" and cloud_provider == "local"

- include_tasks: install_enterprise_security.yml
  when: install_es == "1"

- include_tasks: install_botsv3_dataset.yml
  when: ingest_bots3_data == "1"

- include_tasks: install_dltk.yml
  when: install_dltk == "1"