
- include_tasks: create.yml
  when: join_domain == "1" and cloud_provider != "local"

- include_tasks: create_local.yml
  when: join_domain == "1" and cloud_provider == "local"

- include_tasks: windows-disable-firewall.yml
  when: join_domain == "1"