---
#- include_tasks: install_deb_uf.yml
#- include_tasks: configure_outputs_conf.yml
- include_tasks: nginx_web_proxy.yml
#- include_tasks: create_deploymentclient.yml
- include_tasks: configure_inputs.yml

- name: Restart splunk uf
  become: true
  command: "systemctl restart SplunkForwarder"

- name: restart nginx again
  become: true
  command: "nginx -s reload"
