---
# This playbook contains common tasks in this role

- include_tasks: install_phantom.yml
  when: cloud_provider != "local"

- include_tasks: install_phantom_local.yml
  when: cloud_provider == "local"