---

- include_tasks: install_osquery_linux.yml
- include_tasks: collect_osquery_logs.yml

- name: Restart splunk uf
  become: true
  command: "systemctl restart SplunkForwarder"
  when: cloud_provider != "local"

- name: Restart splunk uf
  become: true
  command: "/opt/splunkforwarder/bin/splunk restart"
  when: cloud_provider == "local"