---
- include_tasks: install_deb_uf.yml
- include_tasks: configure_outputs_conf.yml
- include_tasks: install_sysmon_linux.yml
- include_tasks: create_deploymentclient.yml
- include_tasks: configure_inputs.yml

- name: restart splunk
  become: true
  command: "systemctl restart SplunkForwarder"